### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by xMisio72** [tarikjaber/Bulk-URL-Opener#2]
Hi, 
I've been using the plug-in for a few months now and suddenly I got this error message and I don't know why (and all of my other plug-ins are still working fine). I would appreciate some help! Thank you very much!

[2024-01-24.txt](https://github.com/tarikjaber/Bulk-URL-Opener/files/14043503/2024-01-24.txt)

```
Flow Launcher version: 1.16.2
OS Version: 22621.3007
IntPtr Length: 8
x64: True

Python Path: C:\Users\basti\AppData\Roaming\FlowLauncher\PythonEmbeddable\pythonw.exe
Node Path: 
Date: 01/24/2024 21:40:11
Exception:
Bulk URL Opener Exception: 
Websites: https://github.com/tarikjaber/Bulk-URL-Opener
Author: Tarik Jaber
Version: 1.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\basti\AppData\Roaming\FlowLauncher\Plugins\Bulk URL Opener-1.1.0\main.py", line 67, in <module>
    TabOpener()
  File "C:\Users\basti\AppData\Roaming\FlowLauncher\Plugins\Bulk URL Opener-1.1.0\lib\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\basti\AppData\Roaming\FlowLauncher\Plugins\Bulk URL Opener-1.1.0\main.py", line 18, in query
    browser_name = self.rpc_request['settings']['default_browser']
TypeError: 'NoneType' object is not subscriptable

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\basti\AppData\Roaming\FlowLauncher\Plugins\Bulk URL Opener-1.1.0\main.py", line 67, in <module>
    TabOpener()
  File "C:\Users\basti\AppData\Roaming\FlowLauncher\Plugins\Bulk URL Opener-1.1.0\lib\flowlauncher\FlowLauncher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\basti\AppData\Roaming\FlowLauncher\Plugins\Bulk URL Opener-1.1.0\main.py", line 18, in query
    browser_name = self.rpc_request['settings']['default_browser']
TypeError: 'NoneType' object is not subscriptable

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by tarikjaber** [comment]
Thank you for bringing this up! I believe I have encountered this occasionally myself so I will investigate and try to fix this as soon as possible.

**Comment by tarikjaber** [comment]
I'm going to attempt a fix in version `1.1.1` and test it extensively.

**Comment by xMisio72** [comment]
> Thank you for bringing this up! I believe I have encountered this occasionally myself so I will investigate and try to fix this as soon as possible.

Okay, I haven't found a solution for me yet. I can't use the plug-in at the moment because it crashes every time I try to use a command.
In the meantime, I'm using the old-school way by having bookmark folders in the browser with the websites I want to open and then clicking on the folder with the middle mouse button.
